//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rentals
    {
        public int RentalID { get; set; }
        public Nullable<int> MovieID { get; set; }
        public Nullable<int> CostomerID { get; set; }
        public Nullable<System.DateTime> RentalDate { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
